config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/own_bookings", to: "bookings#own_bookings"
  resources :bookings, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :courses, only: [:create, :new, :update, :destroy, :index, :show] do 
    resources :bookings, except: [:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :bookings, dependent: :destroy
  validates :address, :date, :number_of_places, :time, presence: true

  before_create :add_remaining_places

  private

  def add_remaining_places
    self.remaining_places = self.number_of_places
  end
end

app/models/modal_responder.rb
class ModalResponder < ActionController::Responder
  cattr_accessor :modal_layout
  self.modal_layout = 'modal'

  def render(*args)
    options = args.extract_options!
    if request.xhr?
      options.merge! layout: modal_layout
    end
    controller.render *args, options
  end

  def default_render(*args)
    render(*args)
  end

  def redirect_to(options)
    if request.xhr?
      head :ok, location: controller.url_for(options)
    else
      controller.redirect_to(options)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
    before_action :set_locale

    def respond_modal_with(*args, &blk)
      options = args.extract_options!
      options[:responder] = ModalResponder
      respond_with *args, options, &blk
    end


    def set_locale
      I18n.locale = I18n.default_locale
    end

    protected 
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
  end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json

  def new
    @course = Course.find(params[:course_id])
    @booking = Booking.new
    respond_modal_with @course
  end
  
  def create
    @booking = Booking.new(booking_params)
    @course = Course.find(params[:course_id].to_i)
    @booking.course = @course
    @booking.user = current_user
    if @course.remaining_places >= booking_params[:number_of_people].to_i
      if @booking.save
        redirect_to root_path, notice: "Réservation réussie"
        @course.remaining_places -= @booking.number_of_people.to_i
        @course.save
      else 
        flash[:alert] = "Réservation échouée, veuillez réessayer"
        render :new
      end
    else
      flash[:alert] = "Problème"
    end

  end

  def own_bookings
    @bookings = current_user.bookings
    @upcoming_bookings = @bookings.select do |booking|
      booking.course.date >= Date.today
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @course = @booking.course
    @course.remaining_places += @booking.number_of_people
    @course.save
    @booking.destroy
    redirect_to course_path(@course)
  end

  private 

  def booking_params 
    params.require(:booking).permit(:number_of_people, :user_id, :course_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
    @booking = Booking.new
    @this_week_courses_unsorted = []
    @this_week_courses_unsorted = @courses.select do |course|
      if course.date.cweek == Date.today.cweek
        @this_week_courses_unsorted << course 
      end
    end
    @this_week_courses = @this_week_courses_unsorted.sort_by {|course| course.date}

    @upcoming_courses_unsorted = []
    @upcoming_courses_unsorted = @courses.select do |course|
      if course.date.cweek > Date.today.cweek
        @upcoming_courses_unsorted << course 
      end
    @upcoming_courses = @upcoming_courses_unsorted.sort_by {|course| course.date}
    end

    @passed_courses_unsorted = []
    @passed_courses_unsorted = @courses.select do |course|
      if course.date.cweek < Date.today.cweek
        @passed_courses_unsorted << course 
      end
    end
    @passed_courses = @passed_courses_unsorted.sort_by {|course| course.date}
  end

  def show
    @course = Course.find(params[:id])
  end
  
  def new
    @course = Course.new
  end
  
  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else 
      render :new
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to courses_path
  end

  private 

  def course_params 
    params.require(:course).permit(:address, :date, :time, :number_of_places, :remaining_places)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @courses = Course.all
    @weekly_courses_unsorted = []
    @weekly_courses_unsorted = @courses.select do |course|
      if course.date.cweek == Date.today.cweek
        @weekly_courses_unsorted << course 
      end
    end
    @weekly_courses = @weekly_courses_unsorted.sort_by {|course| course.date }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-sm-4">
    <%= simple_form_for(([@course, @booking]), remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
      <%= f.input :number_of_people, label:"Pour combien de personnes réserves-tu?", collection: 1..@course.remaining_places %>
      <%= f.submit "Réserver", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/own_bookings.html.erb
<div class="container">
  <h2 class="text-center mt-5">Mes réservations à venir</h2>
  <div class="container-home">
    <% @upcoming_bookings.each do |booking| %>
    <div class="course-card col-4 mt-2">
      <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= booking.course.address%></h5>
      <hr>
      <% minutes = booking.course.time.min %>
      <% if minutes < 10 %>
        <% min = "0" + minutes.to_s %>
      <% else %>
        <% min = minutes%>
      <% end %>
      <p><%= "#{booking.course.date.day}/#{booking.course.date.month}/#{booking.course.date.year} - #{booking.course.time.hour}:#{min}" %></p>
      <p><%= "Réservation pour #{booking.number_of_people} personne(s)"%></p>
    </div>
    <% end %>  
  </div>
</div>

app/views/courses/index.html.erb
<% if current_user.admin == true %>
<div class=" mt-5">
  <div class="container-home-white d-flex justify-content-between align-items-center">
    <h2 class="text-left">Tous les cours</h2>
    <%= link_to "Ajouter un cours", new_course_path, class:"btn btn-primary"%>
  </div>

    <div class="container-home">
      <h3>Cours cette semaine</h3>
      <% if @this_week_courses.empty? %>
        <h3>Pas de cours cette semaine</h3>
      <% else %>
        <% @this_week_courses.each do |course|%>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}" %></p>
            <% if course.bookings.empty?%>
              <p>Il reste <%= course.number_of_places%> places</p>
            <% elsif course.remaining_places == 0 %>
            <p>Le cours est complet <%= ["💪","🎉","👯‍♀️", "🤩","🥳"].sample %></p>
            <% else %>
              <p>Il reste <%= course.remaining_places %> place(s)</p>
            <% end %>
            <%= link_to course_path(course), class:"btn btn-outline-primary mb-3" do %>
              <i class="fas fa-users"></i>
            <% end %>
            <%= link_to course_path(course),
            method: :delete,
            data: { confirm: "Etes-vous sûr de vouloir supprimer ce cours?" },
            class:"btn btn-outline-primary mb-3" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="container-home">
    <h3>Cours à venir</h3>
      <% if @upcoming_courses.empty? %>
        <h3>Pas de cours à venir</h3>
      <% else %>
        <% @upcoming_courses.each do |course|%>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}" %></p>
            <% if course.bookings.empty?%>
              <p>Il reste <%= course.number_of_places%> places</p>
            <% elsif course.remaining_places == 0 %>
            <p>Le cours est complet <%= ["💪","🎉","👯‍♀️", "🤩","🥳"].sample %></p>
            <% else %>
              <p>Il reste <%= course.remaining_places %> place(s)</p>
            <% end %>
            <%= link_to course_path(course), class:"btn btn-outline-primary mb-3" do %>
              <i class="fas fa-users"></i>
            <% end %>
            <%= link_to course_path(course),
            method: :delete,
            data: { confirm: "Etes-vous sûr de vouloir supprimer ce cours?" },
            class:"btn btn-outline-primary mb-3" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>


    <div class="container-home">
      <h3>Cours passés</h3>
      <% if @passed_courses.empty? %>
        <h3>Pas de cours passés</h3>
      <% else %>
        <% @passed_courses.each do |course|%>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}" %></p>
            <% if course.bookings.empty?%>
              <p>Il reste <%= course.number_of_places%> places</p>
            <% elsif course.remaining_places == 0 %>
            <p>Le cours était complet <%= ["💪","🎉","👯‍♀️", "🤩","🥳"].sample %></p>
            <% else %>
              <p>Il restait <%= course.remaining_places %> place(s)</p>
            <% end %>
            <%= link_to course_path(course), class:"btn btn-outline-primary mb-3" do %>
              <i class="fas fa-users"></i>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>
<% else %>
  <div class="container-home">
      <h3>Cours cette semaine</h3>
      <% if @this_week_courses.empty? %>
        <h3>Pas de cours cette semaine</h3>
      <% else %>
        <% @this_week_courses.each do |course|%>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}" %></p>
            <% if course.bookings.empty?%>
              <p>Il reste <%= course.number_of_places%> places</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2' %>
              <p><em>Prix: 10€</em></p>
            <% elsif course.remaining_places == 0 %>
              <p>Ce cours est complet</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2 disabled', disabled: true %>
              <p><em>Prix: 10€</em></p>
            <% else %>
              <p>Il reste <%= course.remaining_places %> place(s)</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2' %>
              <p><em>Prix: 10€</em></p>
            <% end %>            
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="container-home">
    <h3>Cours à venir</h3>
      <% if @upcoming_courses.empty? %>
        <h3>Pas de cours à venir</h3>
      <% else %>
        <% @upcoming_courses.each do |course|%>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}" %></p>
            <% if course.bookings.empty?%>
              <p>Il reste <%= course.number_of_places%> places</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2' %>
              <p><em>Prix: 10€</em></p>
            <% elsif course.remaining_places == 0 %>
              <p>Ce cours est complet</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2 disabled', disabled: true %>
              <p><em>Prix: 10€</em></p>
            <% else %>
              <p>Il reste <%= course.remaining_places %> place(s)</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2' %>
              <p><em>Prix: 10€</em></p>
            <% end %>            
          </div>
        <% end %>
      <% end %>
    </div>
<% end %>

app/views/courses/new.html.erb
<div class="container mt-5">
  <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-sm-4">
    <div class="container">
      <h2>Créer un cours</h2>
      <%= simple_form_for(@course) do |f| %>
        <%= f.input :address, label:"Adresse" %>
        <%= f.input :date %>
        <%= f.input :time, label:"Heure"%>
        <%= f.input :number_of_places, label:"Nombre de places" %>
        <%= f.button :submit,"Créer le cours", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container">
  <h2 class="text-center mt-4"><%= "#{@course.address} - #{@course.date.day}/#{@course.date.month}/#{@course.date.year}"%></h2>
  <h3 class="text-center">Liste des participants</h3>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">Prénom</th>
        <th scope="col">Email</th>
        <th scope="col">Nombre de personnes</th>
        <th>Supprimer</th>   
      </tr>  
    </thead>


    <% @course.bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.first_name %></td>
        <td><%= booking.user.last_name %></td>
        <td><%= booking.user.email %></td>
        <td><%= booking.number_of_people %></td>
        <td>
            <%= link_to booking_path(booking),
            method: :delete,
            data: { confirm: "Etes-vous sûr de vouloir supprimer cette réservation?" } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
        </td>
      </tr>
    <%end%>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&amp;display=swap" rel="stylesheet">
    <title>Lucifit - cours de trampoline</title>
    <%= favicon_link_tag %>
    <meta name="description" content="Envie de découvrir un sport qui va enfin vous motiver à vous bouger tout en vous amusant? Cours de trampoline à Andenne et Ohey." />
    <meta property="og:title" content="Lucifit - cours de trampoline">
    <meta property="og:description" content="Envie de découvrir un sport qui va enfin vous motiver à vous bouger tout en vous amusant? Cours de trampoline à Andenne et Ohey.">
    <meta property="og:image" content="https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-9/104017723_165586911633094_3351656514515100403_n.jpg?_nc_cat=103&_nc_sid=8bfeb9&_nc_ohc=mCRoAf6BLdUAX9QgssD&_nc_ht=scontent-bru2-1.xx&oh=1a819df3ec90ce793a16c67e50779dd4&oe=5FB80159">
    <meta property="og:url" content="https://www.lucifit.be">
  </head>

  <body class="bg-white">
    <div>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flashes' %>
    <div id="modal-holder"></div>
    <%= yield %>    
    </div>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.5)), url(<%= image_path "group-of-fit-female-friends-3822725.jpg" %>);">
    <div id="text-banner">
      <h1>Lucifit</h1>
      <p>Cours de trampoline</p>
    </div>
  </div>

  <div id="description" class="container-home">
    <h2>Envie de découvrir un sport qui va enfin vous motiver à vous bouger tout en vous amusant?</h2>
    <p>Lucifit vous prépare chaque semaine un cours de trampoline
      Groupe de 10 personnes max, chaque cours dure 1h.
      L'opportunité parfaite pour vous défouler tout en brûlant des calories.
    </p>
  </div>

  <div id="planning" class="container-home">
    <h2>Planning de la semaine</h2>
    <% if @weekly_courses.empty? %>
      <h3>Pas de cours cette semaine</h3>
    <% else %>
      <% @weekly_courses.each do |course|%>
        <% if course.date >= Date.today %>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}"%></p>
            <% if course.remaining_places > 0 %>
              <p>Il reste <%= course.remaining_places%> places</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2' %>
              <p><em>Prix: 10€</em></p>
            <% else %>
              <p class="text-primary font-weight-bold">Ce cours est complet</p>
              <%= link_to 'Réserver', new_course_booking_path(course), class: 'btn btn-primary mb-2 disabled', disabled: true %>
            <% end %>
          </div>
        <% else %>
          <div class="course-card col-10 col-lg-4 mt-3">
            <h5 class="pt-3"><i class="fas fa-map-marker-alt"></i> <%= course.address%></h5>
            <hr>
            <% minutes = course.time.min %>
            <% if minutes < 10 %>
              <% min = "0" + minutes.to_s %>
            <% else %>
              <% min = minutes%>
            <% end %>
            <p><%= "#{course.date.day}/#{course.date.month}/#{course.date.year} - #{course.time.hour}:#{min}"%></p>
            <p class="text-primary font-weight-bold">Ce cours est déjà passé</p>
          </div>
        <%end%>
      <% end %>
    <% end %>
    <div class="link-extra-courses">
      <%= link_to "Voir tous les cours planifiés", courses_path %>
    </div>
  </div>

  <div class="container-home">
    <h2>Qui suis-je?</h2>
    <p> Je m'appelle Lucie Mathieu et j'habite à Ohey.
      Il y a quelques années, j'ai suivi un cours de trampoline
      et je suis tombée amoureuse de ce sport. Je voulais partager
      cette nouvelle passion avec d'autres personnes, c'est pourquoi
      j'ai suivi une formation pour pouvoir donner mes propres cours de
      trampoline. <br>
      Je suis une personne pleine d'énergie et de créativité, et je fais
      de mon mieux pour que chaque cours soit une partie de plaisir pour
      tout le monde!
    </p>
  </div>

  <div class="container-home">
    <h2>En savoir plus</h2>
    <p>Si vous voulez plus d'information ou si vous avez des questions,
      n'hésitez pas à me contacter!
    </p>
    <div id="contact-details">
      <p><i class="fas fa-mobile"></i> 0496 91 12 21</p>
      <p><i class="fas fa-envelope"></i> lucie.mathieu93@hotmail.com</p>
    </div>
  </div>

<footer>
  <h4>Suivez-moi sur Facebook:</h4>
  <p><a href="https://www.facebook.com/LuciFit-110557990469320" target="_blank"><i class="fab fa-facebook"></i></a></p>

  <div class="footer bg-black small text-center text-black-50"><div class="container mb-4">Copyright © Unloqd 2020</div></div>
</footer>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <li class="nav-item <%= "active" if current_page?(courses_path)%>">
            <%= link_to "Liste des cours", courses_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if current_page?(new_course_path)%>">
            <%= link_to "Ajouter un cours", new_course_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Me déconnecter",  destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else%>
          <li class="nav-item <%= "active" if current_page?(root_path)%>">
            <%= link_to "Page d'accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if current_page?( own_bookings_path)%>">
            <%= link_to "Mes réservations", own_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Me déconnecter",  destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item <%= "active" if current_page?(new_user_registration_path)%> ">
          <%= link_to "M'inscrire", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= "active" if current_page?(new_user_session_path)%>">
          <%= link_to "Me connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>